FROM wizardsofindustry/aorta:latest
LABEL maintainer="operations@wizardsofindustry.net"

RUN mkdir -p /etc/aorta/routes.conf.d
RUN mkdir -p /var/spool/aorta
ENTRYPOINT ["python3.6","-m","aorta.router","--spool","/var/spool/aorta"]
